spring:
  # profiles
  profiles:
    active: prod

  # application
  application:
    name: JavaPractice

  # jpa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true

  # cache
  cache:
    type: redis

  # messages
  messages:
    fallbackToSystemLocale: false
    encoding: UTF-8
    basename: i18n/messages

  # task
  task:
    execution:
      pool:
        max-size: 16
        core-size: 16
        keep-alive: 10s
        queue-capacity: 100
        allow-core-thread-timeout: true
      thread-name-prefix: async-task-

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.knight.javaPractice.entity
  configuration:
    map-underscore-to-camel-case: true

# jwt
jwt:
  tokenHeader: Authorization
  secret: personal-java-practice
  expiration: 604800
  tokenHead: 'Bearer '

# secure
secure:
  ignored:
    urls:
      - /favicon.ico
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /actuator/**
      - /druid/**
      - /error
      - /users/**
      - /jpa/**

# management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

# server
server:
  shutdown: graceful
